<?php

/**
 * author: Jayin <tonjayin@gmail.com>
 */

namespace Queue\Libs\Queues;

use Queue\Libs\Queue;
use Queue\Model\JobModel;

/**
 * 基于数据库的队列
 */
class DatabaseQueue extends Queue {

    /**
     * @var JobModel
     */
    private $db;

    public function __construct() {
        $this->connect();
    }


    protected function connect() {
        $this->db = D('Queue/Job');
    }

    public function push($queue = '', \Job $job) {
        return parent::push($queue, $job); // TODO: Change the autogenerated stub
    }

    public function pop($queue = '') {
        return parent::pop($queue); // TODO: Change the autogenerated stub
    }

    public function size() {
        parent::size(); // TODO: Change the autogenerated stub
    }


}